### ISSUE TITLE
kots CLI: kots install with --license-file hangs after "Creating base" with no feedback

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#450]
```
 k kots install my-kots-app --license-file ~/Desktop/path/to/license.yaml
```

Output gets to here and then just hangs for minutes 

```
Enter the namespace to deploy to: my-kots-app

  • Pulling upstream ✓  
  • Creating base ✓  
```

I'm guessing this is starting datastores, apis, etc but we lose all the regular `kubectl kots install` output.

**Update** after several minutes I get this:

```
  • Creating base ✓  
  • Creating midstream ✓  
  • Creating downstream "this-cluster" ✓  
  • Deploying Admin Console
    • Creating namespace ✓  
    • Waiting for datastore to be ready ✓  
Enter a new password to be used for the Admin Console: 
```

**Comment by marccampbell** [comment]
@dexhorthy currently in KOTS, when you pass a licensefile arg in the CLI, it does the render (pull, create base, etc) all in the CLI.  There's no missing output, but the actions that normally take place in kotsadm are relocated to take place in the cli output. This can be slow to render if there are many helm charts ,etc.  It's always going to be slower to render than the normal workflow which simply creates the admin console in the cluster.

I don't think what we are doing here is right, I'm describing how it works today after looking at the code.

We should explore if there's a way to pass the license file in and keep the workflow the same, but repurpose this CLI flag as an automation flag instead of a big-fork-in-execution flag

**Comment by dexhorthy** [comment]
@marccampbell for very large apps, I'm wondering if we need to start thinking of a way to dedupe elements in the tar stream. For example, if my 20MB helm chart tar.gz is totally unchanged, maybe we can eliminate it from the tar stream somehow.

I think this is getting off topic, I can open a separate issue for that conversation.

**Comment by MikaelSmith** [comment]
I'm not sure if this is the same but I'm also running into issues with `--license-file`:
```
$ kubectl kots install cd4pe/unstable --license-file license.yaml
Enter the namespace to deploy to: cd4pe

  • Pulling upstream ✓
  • Creating base ✓
  • Creating midstream ✓
  • Creating downstream "this-cluster" ✓
  • Deploying Admin Console
    • Creating namespace ✓
    • Waiting for datastore to be ready ✓
Enter a new password to be used for the Admin Console: ••••••••••
  • Waiting for Admin Console to be ready ✓
Application name: kotsadm042477586
  • Uploading local application to Admin Console ✗
Error: failed to unmarshal response: invalid character '<' looking for beginning of value
```
The same seems to work fine if I omit `--license-file` and use the same file in the console workflow.

**Comment by dexhorthy** [comment]
@MikaelSmith I think that might be a separate issue -- would you mind opening a second one.

Update for everyone else: the long hanging while creating the base is mostly, as noted, due to the very large app being used (lots of YAML).

**Comment by MikaelSmith** [comment]
Filed as #455.
