### ISSUE TITLE
CLI doesn't respect context namespace

### ISSUE THREAD

**Issue by robbiet480** [replicatedhq/kots#478]

**Comment by cbodonnell** [comment]
As of [v1.89.0](https://docs.replicated.com/release-notes/rn-app-manager#bug-fixes-1-89-0), the kots CLI will utilize the namespace of the current context if one is not explicitly provided.  This applies to all commands except for the `kots install` command since the user is prompted for a namespace if one is not provided via CLI flag.

PR: https://github.com/replicatedhq/kots/pull/3286
