### ISSUE TITLE
kotsadm: ability to retry a deployment

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#502]
Often I'll get an error during deployment in kotsadm, which requires manual steps to address. Once I've taken these manual steps, there's no way to retry the deployment. Examples include:

- errors on immutable fields like Jobs and Statefulsets -- I would manually delete the resource and then re-deploy
- errors due to missing API versions - I would apply the CRDs and then re-deploy

I know some of these can be addressed by preflight checks, but there's no way to re-run those either (that might be worth a separate issue though)

**Comment by nikogura** [comment]
In my case, the culprit is a PVC that I've had to change.  The deployment fails, since the PVC is immutable, and I've forgotten to remove it before deploying.

To remedy, I delete the PVC manually, click 'rollback', and then attempt to deploy again.

The deploy fails with the original error message.  Presumably this error is cached from the initial deployment, as the PVC in question no longer exists.

My only remedy is to manually remove and re-apply the manifest to the cluster (workable, but kind of defeats the purpose of kots), or make a nonsense change to the resources and re- trigger the pipeline.

An explicit 'retry' button that actually attempts to re-apply the application resources would be a nice feature.  It's not a big deal for an unstable application in development, but it will get seriously annoying when this app becomes stable/production worthy.

**Comment by cbodonnell** [comment]
Closing this issue since we now have a "Redeploy" button in the admin console and preflight checks can also be re-run.
