### ISSUE TITLE
kots CLI on kURL embedded cluster: can't use admin-console upgrade command

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#703]
There's been some conversation around this, but want to create a central place for further discussion.

### Background

kurl.sh allows for creating a `curl | bash` script to provision Kubernetes and kotsadm on a bare VM, and also packages the kots CLI along with that install so it can be invoked from the host:

<img width="1385" alt="Screen Shot 2020-06-29 at 8 23 12 AM" src="https://user-images.githubusercontent.com/3730605/86011010-c8734880-b9e1-11ea-84e8-8ee79ab49e22.png">

### Confusion

One question here is, in these sorts of clusters, what is the correct behavior for the `kubectl admin-console upgrade` command? There are a few concerns here:

1. The kots/adm stack installed as a kurl.sh addon should be as close as possible to a `kubectl kots install` -ed cluster, in both functionality and interface 
2. A cluster provisioned with kurl.sh may explicitly pin a version of kotsadm. This version would have been explicitly chosen by an application maintainer who wants to distribute with kURL, and `kubectl kots admin-console` may incidentally upgrade the kotsadm stack outside of range that is verified by the packager
3. If a cluster is upgraded by the kots CLI, and then a kurl.sh install script that pins an older version is run (or re-run), this could even cause a *downgrade* of the in-cluster kots components, which is not at all supported

**Comment by dexhorthy** [comment]
cc @marccampbell feel free to edit or add any additional comments here

**Comment by marccampbell** [comment]
@dexhorthy i don't have much to add to that list. It feels complete.

An application cannot receive updates from two sources of truth, or BadThings may happen. We've intentionally made the `admin-console upgrade` command not work on a kURL cluster installation, so that the kURL installer can manage the upgrades (for the reasons you've enumerated). There is a `--force` flag to override this, but you have to understand that we may run a data migration and then when you want to upgrade Kubernetes using the kURL installer, it would downgrade KOTS and possibly be incompatible with the data.

There's an override, but KOTS today strongly recommends (and makes it not obvious how to change) this behavior to avoid creating unexpected and incopmatible installs.
